### ISSUE TITLE
Unexpected moving behavior with a lot of markers

### ISSUE THREAD

**Issue by jaballogian** [hugobarragon/react-leaflet-drift-marker#4]
Hello there

I'm using this library with dynamic real data from my API to create moving animation markers.
I always request the API and update the marker state (a list of markers) every 10 seconds.
The API would update all the object locations every time I request it.
The object would be motorcycles or cars.

When I tested with only 10 real object data (one object item will be displayed with a marker on the map), the moving animation works as expected.
But when I tested with hundreds (more than 300) of real object data, a lot of markers didn't move as expected. The markers moved unreasonably very fast (around 100 km/second meanwhile the average moving of the object is around 20-30 km/hour).

I'm in Indonesia. The marker could move from the starting point to the finish points I note below (green line) in just a few seconds meanwhile from the west edge to the east edge of the island (blue line) is around 1300 km.
![image](https://user-images.githubusercontent.com/24468466/175479421-5b83eb67-b1fc-4805-9425-6acde69fe70f.png)

My question is have you tried using this library with hundreds of real data?

I wish I could create you a codesandbox with our real data but it's our confidential data.
Perhaps I could create you a codesandbox with nearly closed data soon.

**Comment by hugobarragon** [comment]
Hi, the markers dont move with real time, they dont know how may kilometers there are betewen the start and stop points and at what moving speed km/h they are going.

As it is stated on the docs you have to control the time you want the markers to take to move between points.  

If you placed the duration fro 1s for all points, they will all take 1s to go to the destination point, it does not matter if they are 5km away or 100km away thats data and calculations you have to make, maybe if you want to always look around same speed, you have to calculate the duration of each with the distance, so :
5km away take 1s
10km away take 2s
so that the points dont run across the country at amazing speed
If something is needed, create a sandbox link with fake data simulating the problem i will try to help
<html>
<body>


duration | number |   | Required, duration im miliseconds marker will take to destination point
-- | -- | -- | --



</body>
</html>
