### ISSUE TITLE
WebGL setup

### ISSUE THREAD

**Issue by electroheadfx** [hugobarragon/react-leaflet-drift-marker#8]
Is it possible to show an WebGL setup with drift-marker ?

**Comment by hugobarragon** [comment]
Hi @electroheadfx if there is a need for thousands of points on the map we for that need webgl options, i used and helped to on this lib  

https://github.com/knapcio/react-leaflet-pixi-overlay  

but, be carefull normally [react-leaflet-drift-marker](https://github.com/hugobarragon/react-leaflet-drift-marker) solves every problem, its very very rare a need for webgl, because normally a client with 1000 points on the map, cant see nothing... there are alot you can do if you are having performance problems, code optimization, map filtration to show only point on current view, map filters, for example , per country, per city, per id´s....
